version: '3.5'

services:
  postgres:
    container_name: postgres_demo
    image: postgres:14.8
    networks:
      - pingwit_net
    environment:
      POSTGRES_DB: ping_7
      POSTGRES_USER: pingwit
      POSTGRES_PASSWORD: pingwit_password
    volumes:
      - "vol_postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  carrental-app:
    container_name: carrental-application
    image: pavel-radkevich.class-carrental
    networks:
      - pingwit_net
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/ping_7


networks:
  pingwit_net:
    driver: bridge
    
volumes:
  vol_postgres:
